name: Build Docker Images
on: 
  push:
    branches:
      - main
  workflow_dispatch: 
  pull_request:

jobs:
      createMatrix:
        runs-on: ubuntu-22.04
        steps:
          - name: Checkout
            uses: actions/checkout@v3
    
          - name: Generate Matrix
            id: matrix
            run: |
              # Get a list of all directories that have a Dockerfile
              paths=$((ls -d */Dockerfile) | sed 's/\/Dockerfile//')
              # Add all paths to a json array using jq
              values=$(jq -n --arg array "${paths}" '$array | split("\n")')
              echo matrix=${values} >> $GITHUB_OUTPUT
            working-directory: servers
    
        outputs:
          matrix: ${{ steps.matrix.outputs.matrix }}
    
      docker-build:
        timeout-minutes: 5
        runs-on: ubuntu-22.04
        needs: [createMatrix]
        strategy:
          matrix:
            paths: ${{ fromJson(needs.createMatrix.outputs.matrix) }}
    
        env:
          MATRIX_PATH: ${{ matrix.paths }}
    
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
  
          - name: Build and push
            if: github.event_name == 'push' && github.ref == 'refs/heads/main'
            uses: docker/build-push-action@v4
            with:
              context: "{{defaultContext}}:servers/${{ env.MATRIX_PATH }}"
              push: false
              tags: "quick-hello:${{ env.MATRIX_PATH }}"

          - name: Build Image
            if: github.event_name != 'push'
            uses: docker/build-push-action@v4
            with:
              context: "{{defaultContext}}:servers/${{ env.MATRIX_PATH }}"
              push: false
              tags: "quick-hello:${{ env.MATRIX_PATH }}"
          
          # Testing continues below for non-main workflow
          - name: Test Image
            if: github.event_name != 'push'
            run: | 
              docker run "quick-hello:${{ env.MATRIX_PATH }}"
              cd clients/curl
              ./request.sh
            
          - name: Stop Running Containers 
            if: github.event_name != 'push'
            run: docker stop $(docker ps -a -q)
